### ISSUE TITLE
Running odo "as a server"

### ISSUE THREAD

**Issue by boris** [groupon/odo#161]
Hi! Anyone has experience running Odo as a server? I mean, running it in AWS for example and then using devices to connect to this instance?

Is that a use case for odo?

**Comment by djrenfro** [comment]
HI @boris. Yes, odo can be used remotely so long as any firewall rules allow for connection to the location Odo is running from.  You simply need to target the IP address Odo is at.  Odo also allows for multiple clients connecting to a single instance with each having a unique client id so they can be differentiated.  Please let us know any questions you have.

**Comment by boris** [comment]
Hey @djrenfro, is there any special firewall rules I should take into account? I'm basically allowing tcp ports mentioned here https://github.com/groupon/odo#default-odo-ports but I'm not able to pass through the proxy

**Comment by boris** [comment]
@djrenfro my problem was firewall issues, fixed now. Thanks.
